var GAME_LEVELS = [
  [  "                       |                                                                                ",
     "        o                                                 o  o                                          ",
     "                                                                       o                                ",
     "                                     y             xxx               xxx                                ",
     "              o                             xx!xx    xxx           xxx                                  ",
     "     xx    xx     xxx     xxx                                                                           ",
     "                    xx   xx                      o                                                      ",
     "                     x!!!x              xxx            xx!!!xx                                          ",
     "  @           o      xxxxx                xx              =     xx                                      ",
     " xx           x                   xx       xxx        y                c                                ",
     "  xx         xx y       =         xx                             xxx!!xxx                               ",
     "   xxxx   xxxx                          o                                        o                      ",
     "      x!!!x            xxxx       |             xxx!!xxx                         xxx                    ",
     "      xxxxx        !!!!!!!!!!!!                                                                         ",
     "                                                              y       y                                 ",
     "                                     o o     o o                                                        ",
     "                              xxxxxxxxxxx!!!xxxxxx!!!!xxxxxxx               xxx                         "],
  ["                                                                                                               ",
   "@      x     =          xxx                          |                                                         ",
   "xx     x        o                                                                                              ",
   " x     x     xx   xx     |                                                         xx        x                 ",
   " x     x                             o                                                                         ",
   " x    xx      o   o    x   x                  o                                                                ",
   " x     x               x   x                        xxxxx                                                      ",
   " xx    x     xxxxxxx   x   x      xxx!!xxx    o        xxxx             xxxx                                   ",
   " x     x             y x   x                                             |                                     ",
   " x    xx          o             o         xxx     y                 o                                          ",
   " xx    x          xx           xxxxxx      |         xxxxxx      xxxxxx                                        ",
   " x=    x         xx         o                                                                                  ",
   " x     x       xxx      xx               o   o                                                                 ",
   " x     x  y           xxx!!xxxx      xx       xx            o            o                                     ",
   " x                   xx!!!x                    xxx!!!!!xxx     x        xxxx                                   ",
   "xxxxx                                                    x     x                                               ",
   "!!!!!xxxxx!!xxxxxx                 xxxxxxxxxx            x     x           xxxxxxx!!!!xxxxxx                   ",
   "!!!!!!!!!!!!xx                   =                       x!!!!!x                                o              ",
   "!!!!!!!!!!xxxx                                           x x x x                               xx              "],

  ["      o  o       |      xxxx             xxxxxxxxxx                   xxxxxxxxxx        xxxxxxxxxxx            ",
   " @                        |      y       xxx |  xxx                       |                  |                 ",
   " xx         xxxx!!xxxx                  xx      xx        o                                                    ",
   "  xx      xxx          xxxx                  o           xxxx        o        o                        o       ",
   "   xxx  xxx                    o  o                  xxx  =         xxxx!!!!xxxxxxxxx                 xxx      ",
   "       =       o                 xx                            y                  xxx   =      xxx             ",
   "               xx                !!!!             xxxx                       xx!!xxxx                          ",
   "                       oo                oo                                                                    ",
   "    xxxxxxxxx         xxxxxxxxxxx!!!!!!!xxxxxxxxxxx                                             xxxxx           "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                            y                     x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                             =                  x       ",
   "       !  o  !      |                                         xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx    =     xxx                                                                           ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                             |  y                ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                                     x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                    w                                           ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
